### ISSUE TITLE
require should no longer be used

### ISSUE THREAD

**Issue by doodadjs** [dherman/defense-of-dot-js#6]
'import' should be preferred over 'require' for newer modules.

**Comment by caridy** [comment]
@sickle2 this proposal does not touch on that aspect. enabling `require()` inside a ES standard module is a different topic, and doesn't have technical complications. It is just a matter to discuss whether or not we want to support it. Initial discussions around this topic suggest that it might be Ok if we don't get the imperative version of the import statement anytime soon. Anyhow, out of the scope of this discussion.

**Comment by doodadjs** [comment]
@caridy: I'm afraid that this proposal will add complexities when the ES standard will come. Will we get 3 types of modules ?

**Comment by caridy** [comment]
@sickle2 can you elaborate more?

There is nothing on the spec that will prevent a `hostDefined` global binding to be accessed by a source text record (ES Standard Module). And `require` is just a `hostDefined` binding defined by node. I'm not saying that we should add that or not, I'm saying that there is nothing that will prevent them from doing that based on the spec.
