### ISSUE TITLE
How about to embrace webpack 2 approach?

### ISSUE THREAD

**Issue by alonronin** [dherman/defense-of-dot-js#8]
https://gist.github.com/sokra/27b24881210b56bbaff7

**Comment by caridy** [comment]
@alonronin can you be more specific? what part of the webpack 2 approach are you referencing to, considering that webpack's main target is the web, and we are talking about node here.

**Comment by alonronin** [comment]
I mean a similar behavior as babel or webpack 2 when you can mix ES6 with AMD and CommonJS for requiring modules and it would understand it. Also it understands `import` and `export` and not transform it to CommonJS.

I know it's a bit of a pain, but it is make more sense than using different file extensions.

**Comment by caridy** [comment]
This proposal includes the ability to mix CJS and ES Standard Modules in the same package via `modules` directive in package.json. As for AMD, node doesn't support AMD today, and users are forced to use a custom loader for them. As for transformation to CJS, this proposal doesn't transform anything, it uses the native parser for ES Standard Modules.
