### ISSUE TITLE
module directive?

### ISSUE THREAD

**Issue by gibson042** [dherman/defense-of-dot-js#9]
I asked [on Twitter](https://twitter.com/gibson042/status/726602246218211331), but you might have missed it:

> "npm-module" directive would be package.json-compatible and standardizeable as e.g. "use module". Thoughts?

Have you considered identifying modules by a directive at the start of their body? It can work now, is compatible with everything here, and as an approach can be standardized in ECMAScript.

**Comment by caridy** [comment]
@gibson042 the first link from the proposal links out to the original proposals, which touch on why we can't do a pragme: https://github.com/nodejs/node/wiki/ES6-Module-Detection-in-Node#option-1-in-source-pragma-rejected
